[build]
  publish = "."
  command = ""

[[headers]]
  for = "/widget.js"
  [headers.values]
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/embed-example.html"
  status = 200
