[build]
  base = "backend-deploy"
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "mongoose", "openai", "cors", "@aws-sdk/credential-providers", "mongodb", "mongodb-client-encryption", "bson", "@mongodb-js/zstd"]
  node_bundler = "esbuild"
  node_version = "20.x"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
