[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/cors-handler"
  status = 200
  force = true
  conditions = { Method = ["OPTIONS"] }

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  conditions = { Method = ["GET", "POST"] }
